### ISSUE TITLE
/friends does not work for some players

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#840]
No player output.

```
[09:29:58 WARN]: net.avicus.quest.database.DatabaseException: java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 7 to TIMESTAMP.
[09:29:58 WARN]:        at net.avicus.quest.model.ModelList.addRows(ModelList.java:31)
[09:29:58 WARN]:        at net.avicus.quest.model.ModelSelect.execute(ModelSelect.java:66)
[09:29:58 WARN]:        at net.avicus.hook.mysql.table.SessionTable.findLatest(SessionTable.java:19)
[09:29:58 WARN]:        at net.avicus.hook.friends.FriendCommands$1.run(FriendCommands.java:44)
[09:29:58 WARN]:        at net.avicus.hook.utils.Task$1.run(Task.java:91)
[09:29:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[09:29:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[09:29:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09:29:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09:29:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[09:29:58 WARN]: Caused by: java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 7 to TIMESTAMP.
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[09:29:58 WARN]:        at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1337)
[09:29:58 WARN]:        at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:127)
[09:29:58 WARN]:        at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6754)
[09:29:58 WARN]:        at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:6073)
[09:29:58 WARN]:        at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:5029)
[09:29:58 WARN]:        at net.avicus.quest.query.Row.<init>(Row.java:18)
[09:29:58 WARN]:        at net.avicus.quest.model.ModelList.addRows(ModelList.java:29)
[09:29:58 WARN]:        ... 9 more
[09:29:58 WARN]: Caused by: java.sql.SQLException: Value '[B@300710b6' can not be represented as java.sql.Timestamp
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[09:29:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[09:29:58 WARN]:        at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1035)
[09:29:58 WARN]:        ... 15 more

```

**Comment by thekeenant** [comment]
Fixed
